# -*- coding: utf-8 -*-
"""Z Score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m0EQOdJJbuvu_g-onm9TvHnyzqNML80U

**Step 1 :Libraries Import**
"""

import numpy as np
import pandas as pd
import scipy.stats as stats

"""**Step 2: Create an array of values**"""

data = np.array([6,5,5,4,7,8,9,22,15,36])

"""**Step 3: Calculate the z-scores for each value in array...**"""

stats.zscore(data)